### ISSUE TITLE
Register Endpoint - More Detailed response when specifying invalid parameters

### ISSUE THREAD

**Issue by Raistlfiren** [FAForever/api#121]
@Brutus5000 - Could you add an error message if one or more parameters are not specified on the `/register` endpoint. For example, if I pass `name`, `pw_hash`, and `emaily`(notice the 'y' on email) it gives me a 500 error instead of any valid response. In the route it might be better to just have an error message saying `Parameter x is required...`.

Thanks!

**Comment by Brutus5000** [comment]
PR in #122
