### ISSUE TITLE
oauth authorize site requires content from test.faforever.com

### ISSUE THREAD

**Issue by duk3luk3** [FAForever/api#152]
This leads to terrible delays because one of the things it includes doesn't exist anymore. Also the hardcoding to test.faforever.com is terrible.

I think all dependencies should be removed.

**Comment by micheljung** [comment]
Thanks for fixing it. As you can see in my review, there was a `TODO` on top of it, because it was a temporary solution. I'd really appreciate if you could reduce your usages of "terrible", especially in explicitly declared quickfixes like this one was. It doesn't add any value.

**Comment by duk3luk3** [comment]
Sorry. It wasn't meant as a personal slight against you. I shouldn't have written it that way.
