### ISSUE TITLE
Internal Server Error on map upload

### ISSUE THREAD

**Issue by micheljung** [FAForever/api#160]
Reported by JeroenDeDauw in FAForever/downlords-faf-client#510:

Full report: http://forums.faforever.com/viewtopic.php?f=53&t=13467

TL;DR: map itself works fine. Uploading the old version (that everyone is still playing) results in the same error.

**Comment by micheljung** [comment]
Wrong repo

**Comment by JeroenDeDauw** [comment]
What is the correct repo then? You already moved this report once.

**Comment by Sheeo** [comment]
It's the other API. Could we have a direct link, though?

**Comment by JeroenDeDauw** [comment]
A direct link to what? And what other API?

Reporting this bug is turning out to be quite difficult :)
