### ISSUE TITLE
Implement Player stats

### ISSUE THREAD

**Issue by IDragonfire** [FAForever/api#2]
Implement Player stats over D3.js

**Comment by IDragonfire** [comment]
Atm D3.js is a cloud for me ...
Maybe the libary is a little bit overpowered for this task ...
Or we use:
http://nvd3.org/examples/line.html
http://dimplejs.org/examples_viewer.html?id=areas_horizontal_stacked

**Comment by micheljung** [comment]
The API delivers data, it does not visualize them in any way. This belongs to the FAF website, client or elswhere.
