### ISSUE TITLE
CORS support required

### ISSUE THREAD

**Issue by Blodir** [FAForever/api#26]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS

**Comment by Raistlfiren** [comment]
I wonder if it would be as easy as implementing this - https://pypi.python.org/pypi/Flask-Cors/ .... Hmmmm...

**Comment by Sheeo** [comment]
@Raistlfiren yes, or just manually assign the headers and add the option route for preflighting.

**Comment by micheljung** [comment]
Apparently this has been fixed with c982911
