### ISSUE TITLE
Should /bugs be behind oauth? 

### ISSUE THREAD

**Issue by Raistlfiren** [FAForever/api#29]
The logs file are somewhat detailed and include usernames with directory structure from the local computer. I don't think people would like that if we just have it open to the public....

**Comment by Sheeo** [comment]
Indeed, it ought to.

**Comment by micheljung** [comment]
OAuth is not meant protect resources from the public
OAuth is meant to protect *a user's* resources from the public, but allow access to certain *applications*

So if `/bugs` would list the bugs of the current user, then yes, it should be @oauth'd
But to make it only readable by administrators, OAuth is not the way to go. Some role based security model is needed for that.

I'll close this, please file a new issue to protect `/bugs`
