### ISSUE TITLE
Issue with invalid_usage.py

### ISSUE THREAD

**Issue by Raistlfiren** [FAForever/api#32]
Everytime I try to run `./run_local.py` I get the following error: 

`api/api/invalid_usage.py", line 11
    **(self.payload or {}),
     ^
SyntaxError: invalid syntax
`

I can correct the issue by changing the code under to_dict to: 

      if self.payload:
            return self.payload
        d = {
            'code': self.code,
            'message': self.message
        }
        return d

(I am not sure what ** does? Can someone clarify, please)

Thanks!

**Comment by Sheeo** [comment]
Use python 3.5, the ** unpacking syntax was expanded in this python version. Asides from that, other places of the codebase will use `async`/`await`, so 3.5 is a hard requirement.
