### ISSUE TITLE
Issue with auth.py

### ISSUE THREAD

**Issue by Raistlfiren** [FAForever/api#34]
Can you please clarify as to why I keep on running into the following error when I try to do ./run_local.py?

Here is the error: 
```python
Traceback (most recent call last):
  File "run_local.py", line 6, in <module>
    from api import app, api_init
  File "/home/aaron/api-backup/api/api/__init__.py", line 143, in <module>
    import api.auth
  File "/home/aaron/api-backup/api/api/auth.py", line 15, in <module>
    from requests.packages.urllib3.packages import six
ImportError: No module named 'requests.packages'
```

I change `from requests.packages.urllib3.packages import six ` to `import six` and it seems to work just fine. I am now running python3.5.

Thanks!

**Comment by Sheeo** [comment]
So, `run_local.py` doesn't exist any more. Is your local repo up to date?

The code you stumbled into looks weird indeed. Since we're only using Python 3.5+, we shouldn't really need `six`, which is a python 2 compat module.

**Comment by Sheeo** [comment]
I've changed the code here so it doesn't try and shim python 2 support: https://github.com/FAForever/api/commit/304e143c3dd6291a7fed06ec6c0a6935acf40e6a

**Comment by Raistlfiren** [comment]
So I did the following:

`git reset --hard HEAD`
`git checkout upstream/develop`
`python3.5 run.py`

```python
Traceback (most recent call last):
  File "run.py", line 15, in <module>
    from api import app, api_init
  File "/home/aaron/api-backup/api/api/__init__.py", line 137, in <module>
    import api.auth
  File "/home/aaron/api-backup/api/api/auth.py", line 15, in <module>
    from requests.packages.urllib3.packages import six
ImportError: No module named 'requests.packages'
```
I ran `git logs` to make sure I was running the most recent, and it came back with: 

```git
commit 3249f9e5b19863b3a14b5ef86a604e465c81f373
Author: Sheeo <sheeo@faforever.com>
Date:   Tue Feb 23 19:13:28 2016 +0100

    Fix achievement unit tests

commit 6e85def2ebdc68a9fe55239a9952745042554472
Author: Sheeo <sheeo@faforever.com>
Date:   Tue Feb 23 19:03:43 2016 +0100

    Update db submodule

```
