### ISSUE TITLE
Mod upload

### ISSUE THREAD

**Issue by Sheeo** [FAForever/api#39]
Mod upload see [this](https://github.com/FAForever/api/blob/develop/api/mods.py#L33) needs to be finalized.

**Acceptance criteria**

 - Mods are validated for the following requirements prior to insertion:
    - No other mods with conflicting names exist
    - Uploader is authenticated
 - Mods are inserted into the appropriate database table as per current mod structure, though changes are potentially welcome, they should be accompanied by a migration script

**Gotcha**

Nginx on production and the test server currently limit client uploads to 2mb, we need this configuration fixed.

**Comment by micheljung** [comment]
Fixed with #102
