### ISSUE TITLE
Clan support (include webapp)

### ISSUE THREAD

**Issue by Frozen-byte** [FAForever/api#4]
To get a stable Clan support we may include (or rewrite) dragonfire's webapp for Clanmanagement.

Some Features:
Calender for common training times
Subforum which can only seen by Clanmembers (Forumgroup)
Abillity to "challenge" other Clans

**Comment by IDragonfire** [comment]
On the way... 
https://github.com/FAForever/api/pull/10

**Comment by Frozen-byte** [comment]
#10 was merged
