### ISSUE TITLE
 Players rank is always #1 if searched from leaderboards

### ISSUE THREAD

**Issue by Raistlfiren** [FAForever/api#43]
Reference: https://github.com/FAForever/website/issues/16

**Comment by Sheeo** [comment]
"Rank" is not a thing. See discussion in slack.

**Comment by Raistlfiren** [comment]
Well, people would like to know who is first, second, third, fourth, or etc... Should we exclude it from the leaderboards entirely?

**Comment by Sheeo** [comment]
By sorting the leaderboard with http://trueskill.org/#trueskill.TrueSkill.expose (Which the API should be doing), you have an ordering of the kind you want.

Then you just need to label the leaderboard rows.

**Comment by Sheeo** [comment]
I'm still against trying to do this in any way using Trueskill however. This is not the intended use case for the rating system, and once we implement rating decay it will be entirely meaningless.

Please only provide a sort of "rank" for ladder where this notion inherently exists, once that system is back up and running.

**Comment by Raistlfiren** [comment]
The problem is that I need to implement this when filtering by usernames. Whenever I filter - https://github.com/FAForever/api/blob/develop/api/ranked1v1.py#L56

It doesn't return the correct rating. I need to modify that query to append the sub-query - https://github.com/FAForever/api/blob/develop/api/ranked1v1.py#L56

**Comment by Sheeo** [comment]
That needs to go away.

**Comment by Raistlfiren** [comment]
Why, it prevents us from downloading all records from the API.

**Comment by Raistlfiren** [comment]
It doesn't allow people to search by name.

**Comment by duk3luk3** [comment]
How is that an expensive query? It could be optimised by storing the "display ranking" (mean - 3*deviation) as a computed column with an index, but otherwise it appears pretty simple.

**Comment by Sheeo** [comment]
Query itself is simple, but if we're running it for each row, and it requires at least a full index scan. Maybe the query optimizer can turn it into a simpler function during execution -- but I wouldn't bet on that.

This is probably the reason Aulex just made it increment by the row number: https://github.com/FAForever/api/blob/develop/api/ranked1v1.py#L22

**Comment by duk3luk3** [comment]
why the heck does it need to run for each row number, this could just be an ORDER BY expression...
