### ISSUE TITLE
Statistics

### ISSUE THREAD

**Issue by Frozen-byte** [FAForever/api#5]
Will be related to the API, too.

Basically we need pretty, fancy, (un)informatical Statistics for everything.

**Comment by IDragonfire** [comment]
related to #2

**Comment by Frozen-byte** [comment]
#2 is for player statistics in detail. I'm talking about Map / Chat statistics, too. I guess d3.js is possible to extract these, too?

**Comment by micheljung** [comment]
The API delivers data, it does not visualize them in any way. This belongs to the FAF website, client or elswhere.

If you need specific APIs that deliver such data, please open one issue per endpoint.
