### ISSUE TITLE
OAuth: state is missing

### ISSUE THREAD

**Issue by IDragonfire** [FAForever/api#53]
Regarding the OAuth spec the state parameter is missing ...
http://tools.ietf.org/html/rfc6749#section-4.1.2

# How to reproduce
* Add a client to `oauth_clients`
* `oauth/authorize?client_id=123&response_type=code&scope=read`

Reponse was:
`?code=GQODDJCxhUZvfQTYQQwcU9GvuzlOc0`

Expected:
`?code=GQODDJCxhUZvfQTYQQwcU9GvuzlOc0&state=xyz`

**Comment by micheljung** [comment]
> REQUIRED **if a "state" parameter was present in the client authorization request**. The exact value received from the client.

You did not send a state in your request

**Comment by IDragonfire** [comment]
working
