### ISSUE TITLE
Thumbnail URLs are incorrect

### ISSUE THREAD

**Issue by ChrisKitching** [FAForever/api#75]
The `/maps` route returns URLs ending in ".zip" with a "/maps" directory in the middle that should not be there, such as:

http://content.faforever.com/faf/vault/map_previews/large/maps/plateaus_small.v0002.zip

The correct URL is:

http://content.faforever.com/faf/vault/map_previews/large/plateaus_small.v0002.png

**Comment by micheljung** [comment]
Already fixed in 84c0e68
