### ISSUE TITLE
2016-08-08 API update v0.4

### ISSUE THREAD

**Issue by micheljung** [FAForever/api#78]
- [x] Create release v0.4 (git flow)
- [x] Stop API: `docker-compose stop api`
- [x] Migrate database: FAForever/db#28
- [x] Make sure `config.py` contains the following:
```
MAP_UPLOAD_PATH = '/content/faf/vault/maps'
MAP_PREVIEW_PATH = '/content/faf/vault/map_previews'
CONTENT_URL = 'http://content.faforever.com'
```

* [x] Make sure `/opt/stable/vhost.d/api.faforever.com` contains the following (or whatever the proper way is; w/o the proxy_pass, `/maps/upload` resolves to `/etc/nginx/html/maps/upload`. However I feel the proxy_pass should not be necessary?):
```
location /maps/upload {
    client_max_body_size 64m;
    proxy_pass http://api.faforever.com/maps/upload;
}
```

**Comment by Sheeo** [comment]
Nginx complains with the following: ```2016/06/29 17:57:02 [emerg] 55#55: "proxy_pass" cannot have URI part in location given by regular expression, or inside named location, or inside "if" statement, or inside "limit_except" block in /etc/nginx/vhost.d/api.faforever.com:11
nginx: [emerg] "proxy_pass" cannot have URI part in location given by regular expression, or inside named location, or inside "if" statement, or inside "limit_except" block in /etc/nginx/vhost.d/api.faforever.com:11
nginx: configuration file /etc/nginx/nginx.conf test failed```
