### ISSUE TITLE
Map Upload: Handle folder name

### ISSUE THREAD

**Issue by micheljung** [FAForever/api#88]
Currently, the map author has to ensure that the map's folder name is in the form of `name.v0001` and that this name is also used in the `*_scenario.lua` file as well as that the `map_version` is consistent.

We should simplify this process by generating the map folder name ourselves and use it in `map`, `save` and `script` inside the scenario file like so:

```
    map_version = 2,
    map = '/maps/anchor.v0002/Anchor.scmap',
    save = '/maps/anchor.v0002/Anchor_save.lua',
    script = '/maps/anchor.v0002/Anchor_script.lua',
```

Make sure we tell the map authors and document it in the wiki.

**Comment by Blodir** [comment]
:+1:

**Comment by CookieNoob** [comment]
what about maps that contain additional files? As it is now, only the paths for the basic files are adjusted... it would be nice if ALL files would be properly renamed (i.e. the ultimate maps have an additional file called "mapname_tables.lua" which is loaded by the script.lua file).

**Comment by micheljung** [comment]
Yes, filed: #103
