### ISSUE TITLE
scenario.lua is missing when I try to launch a game with a new/updated map

### ISSUE THREAD

**Issue by Justify87** [FAForever/api#93]
1. download one of the new/updated maps (canis forest 4v4, Wonder Open 5v5 NA)
2. host a game with the map
3. Lobby error: scenario.lua missing (scenario.lua is present in the map folders though)

Tested with both faf clients

**Comment by micheljung** [comment]
I can't find any of these maps?

**Comment by Justify87** [comment]
All of these don't work:
![2016-08-24 16_20_48-fa forever 0 11 60 577](https://cloud.githubusercontent.com/assets/10554299/17934099/f3442c88-6a16-11e6-99ab-21296a4f5f50.png)
