### ISSUE TITLE
Map upload explodes scenario file

### ISSUE THREAD

**Issue by seero11** [FAForever/api#94]
If you upload map to vault and then download it, lining from scenario.lua is blown up. 
Instead of lining every line to separated rows, all lines are written in row 1 . This makes further editing really difficult.

**Comment by micheljung** [comment]
I can fix this, meanwhile please us an editor that can handle unix line endings (e.g. Notepad++)

**Comment by micheljung** [comment]
Can you provide me an example please? I just debugged and from what I see, all newlines are preserved

**Comment by micheljung** [comment]
Closed as we didn't get any response.
