### ISSUE TITLE
Upload + Download = Duplicate map in folder

### ISSUE THREAD

**Issue by seero11** [FAForever/api#95]
If i upload **mymap** version 5 to vault and download it, i got renamed duplicate of my map **mymap.v005** to my map folder.

**Comment by micheljung** [comment]
Yes, the only way to avoid this is to either name the directory and files correctly to begin with.
Or let me know if you have a good idea.

**Comment by seero11** [comment]
Is it necessary to rename folders and map files? Could they just overwrite existing ones in map folder? For some reason players were unable to join my games when i had new maps hosted. They got map is missing error, even if they downloaded map from vault manually. Does game check folder names somehow and when host has original map folder and files they seem to be different than players get from vault?
